export const quizSteps = [
  {
    key: "gender",
    title: "What's your gender?",
    subtitle: "This helps us recommend the right styles",
    type: "single" as const,
    options: ["Male", "Female", "Non-binary"],
  },
  {
    key: "age_group",
    title: "What's your age group?",
    subtitle: "Style recommendations vary by age",
    type: "single" as const,
    options: ["18-24", "25-34", "35-44", "45-54", "55+"],
  },
  {
    key: "height",
    title: "What's your height range?",
    subtitle: "Helps us suggest proportional outfits",
    type: "single" as const,
    options: ["Under 5'4\"", "5'4\" - 5'7\"", "5'7\" - 5'10\"", "5'10\" - 6'1\"", "Over 6'1\""],
  },
  {
    key: "weight",
    title: "What's your weight range?",
    subtitle: "For better fit recommendations",
    type: "single" as const,
    options: ["Under 50 kg", "50-65 kg", "65-80 kg", "80-100 kg", "Over 100 kg"],
  },
  {
    key: "body_type",
    title: "What's your body type?",
    subtitle: "Different body types suit different styles",
    type: "single" as const,
    options: ["Ectomorph (lean/long)", "Mesomorph (muscular/medium)", "Endomorph (soft/round)"],
  },
  {
    key: "skin_tone",
    title: "What's your complexion?",
    subtitle: "Helps us recommend complementary colors",
    type: "single" as const,
    options: ["Fair", "Light", "Medium", "Olive", "Tan", "Dark", "Deep"],
  },
  {
    key: "preferred_fit",
    title: "What fit do you prefer?",
    subtitle: "Your comfort zone matters",
    type: "single" as const,
    options: ["Slim fit", "Regular fit", "Oversized / Relaxed"],
  },
  {
    key: "style_preferences",
    title: "What fashion styles do you love?",
    subtitle: "Select all that apply",
    type: "multi" as const,
    options: ["Streetwear", "Casual", "Formal", "Minimal", "Sporty", "Bohemian", "Vintage", "Preppy"],
  },
  {
    key: "style_preferences",
    title: "What fashion styles do you love?",
    subtitle: "Select all that apply",
    type: "multi" as const,
    options: ["Streetwear", "Casual", "Formal", "Minimal", "Sporty", "Bohemian", "Vintage", "Preppy"],
  },
];

export const occasions = [
  { id: "casual", label: "Casual Daily Wear", icon: "☀️" },
  { id: "office", label: "Office / Professional", icon: "💼" },
  { id: "college", label: "College", icon: "📚" },
  { id: "date", label: "Date Night", icon: "💕" },
  { id: "party", label: "Party", icon: "🎉" },
  { id: "wedding", label: "Wedding", icon: "💍" },
  { id: "interview", label: "Interview", icon: "🤝" },
  { id: "gym", label: "Gym / Fitness", icon: "💪" },
  { id: "travel", label: "Travel", icon: "✈️" },
  { id: "summer", label: "Summer Outfits", icon: "🌴" },
  { id: "winter", label: "Winter Outfits", icon: "❄️" },
];
